# Generated by Django 4.1.4 on 2023-01-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_topic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('posts', models.ManyToManyField(to='blog.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
