# Generated by Django 4.1.4 on 2023-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_place_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='places',
            field=models.ManyToManyField(to='blog.place'),
        ),
    ]
